import google.generativeai as genai
from groq import Groq
from dotenv import load_dotenv
import os
import time

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")

FREE_MODELS = [
    {
        "name": "gemini-2.5-flash",
        "provider": "gemini",
        "model": "gemini-2.5-flash",
        "enabled": bool(GEMINI_API_KEY)
    },
    {
        "name": "Gemini 1.5 Flash",
        "provider": "gemini",
        "model": "gemini-1.5-flash-latest",
        "enabled": bool(GEMINI_API_KEY)
    },
    {
        "name": "Llama 3.3 70B",
        "provider": "groq",
        "model": "llama-3.3-70b-versatile",
        "enabled": bool(GROQ_API_KEY)
    },
    {
        "name": "Llama 3.1 70B",
        "provider": "groq",
        "model": "llama-3.1-70b-versatile",
        "enabled": bool(GROQ_API_KEY)
    },
    {
        "name": "Mixtral 8x7B",
        "provider": "groq",
        "model": "mixtral-8x7b-32768",
        "enabled": bool(GROQ_API_KEY)
    }
]

def analyze_with_gemini(prompt, model_name="gemini-1.5-pro-latest"):
    try:
        genai.configure(api_key=GEMINI_API_KEY)
        model = genai.GenerativeModel(model_name)
        response = model.generate_content(
            prompt,
            generation_config=genai.GenerationConfig(
                temperature=0.4,
                top_p=0.95,
                max_output_tokens=8192,
            )
        )
        return response.text
    except Exception as e:
        error_msg = str(e).lower()
        if "429" in error_msg or "quota" in error_msg or "rate limit" in error_msg or "resource_exhausted" in error_msg:
            raise Exception("RATE_LIMIT")
        raise Exception(f"Gemini Error: {str(e)}")


def analyze_with_groq(prompt, model_name="llama-3.3-70b-versatile"):
    try:
        client = Groq(api_key=GROQ_API_KEY)
        response = client.chat.completions.create(
            model=model_name,
            messages=[
                {
                    "role": "system", 
                    "content": "You are an expert UX/QA analyst conducting comprehensive website audits. Provide detailed, actionable insights."
                },
                {
                    "role": "user", 
                    "content": prompt
                }
            ],
            temperature=0.4,
            max_tokens=8000,
            top_p=0.95
        )
        return response.choices[0].message.content
    except Exception as e:
        error_msg = str(e).lower()
        if "429" in error_msg or "rate_limit" in error_msg:
            raise Exception("RATE_LIMIT")
        raise Exception(f"Groq Error: {str(e)}")


def analyze_crawl(crawl_data, transitions):
    crawl_summary = []
    for i, log in enumerate(crawl_data):
        crawl_summary.append(f"""
Page {i+1}: {log['url']}
- Interactive Elements Found: {len(log['buttons'])}
- Elements: {', '.join(log['buttons'][:10])}{'...' if len(log['buttons']) > 10 else ''}
""")
    
    transition_summary = []
    errors = []
    
    for i, trans in enumerate(transitions):
        if trans.get('error'):
            errors.append(f"Error on '{trans['clicked']}': {trans['error']}")
        transition_summary.append(f"""
Transition {i+1}:
- From: {trans['from']}
- Clicked: "{trans['clicked']}"
- To: {trans['to']}
- Status: {'ERROR' if trans.get('error') else 'Success'}
""")
    
    prompt = f"""
You are an expert UX/QA analyst conducting a comprehensive website audit.

## CRAWL SUMMARY
Total Pages Crawled: {len(crawl_data)}
Total Interactions Tested: {len(transitions)}
Errors Encountered: {len(errors)}

## PAGES ANALYZED
{''.join(crawl_summary)}

## NAVIGATION TRANSITIONS
{''.join(transition_summary)}

## ERRORS FOUND
{chr(10).join(errors) if errors else 'No errors detected'}

---

Please provide a detailed UX/QA analysis report covering:

1. Navigation and structure
2. Interactive elements
3. Accessibility issues
4. UX patterns and design
5. Technical issues
6. Recommendations
7. UX score
8. UI score
"""

    enabled_models = [m for m in FREE_MODELS if m["enabled"]]
    
    if not enabled_models:
        return """
No AI Models Available

Add at least one API key in .env:
GEMINI_API_KEY=your_key
GROQ_API_KEY=your_key
"""

    for model_config in FREE_MODELS:
        if not model_config["enabled"]:
            continue
        
        try:
            provider = model_config["provider"]
            model_name = model_config["model"]
            start_time = time.time()
            
            if provider == "gemini":
                report = analyze_with_gemini(prompt, model_name)
            elif provider == "groq":
                report = analyze_with_groq(prompt, model_name)
            else:
                continue
            
            elapsed = time.time() - start_time
            
            model_info = f"""
---
Analysis Generated By: {model_config['name']} ({provider.upper()})
Model: {model_name}
Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}
Processing Time: {elapsed:.2f} seconds
Status: FREE Model
---

"""
            
            report = model_info + report
            
            os.makedirs("reports", exist_ok=True)
            report_file = f"reports/ux_analysis_{len(crawl_data)}pages_{int(time.time())}.md"
            with open(report_file, "w", encoding="utf-8") as f:
                f.write(report)
            
            return report
            
        except Exception as e:
            error_msg = str(e)
            if "RATE_LIMIT" in error_msg:
                continue
            else:
                continue
    
    error_report = f"""
All AI Models Failed

Pages Crawled: {len(crawl_data)}
Transitions: {len(transitions)}
Errors: {len(errors)}

Solutions:
Add Groq API Key (Free)
Retry later
"""

    return error_report
